defaults:
  - _self_
_target_: lib.model.mde.latentvae.latentvae_pipeline.Pipeline
dpt_args: 
  encoder: 'vitl'
  localhub: False
loss_args:
  _target_: lib.model.mde.loss.sil_loss.SILogLoss
vae_path: ${oc.env:workspace}/Marigold/checkpoint/Marigold_v1_merged_2/vae
  

