# @package _global_
defaults:
  - override /data: mde/hypersim_byte
  - override /model: mde/mde_marigold_upsample
  - override /callbacks: 
    - model_checkpoint_simple
    - train_speed_timer

pl_trainer:
  precision: 16-mixed
  limit_train_batches: 10000
  limit_val_batches: 100
  max_epochs: 100
  log_every_n_steps: 50
  accumulate_grad_batches: 1 # * 8 if use only one gpu

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir} # /save_dir/name/version/sub_dir
  name: ""
  version: "tb" # merge name and version

task: mde
exp_name: mde_upsample_baseline_0404_byte

model:
  pipeline:
    args:
      zerosft_modulated_rgb: True
      linear_sample: True
      # DEBUG
      zerosft:
        _target_: lib.model.mde.utils.zerosft.ZeroSFT
        label_nc: 5
        norm_nc: 4
      unet_opt:
        config_dir: ${oc.env:workspace}/Marigold/checkpoint/Marigold_v1_merged_2/unet # stable diffusion v2 unet