# @package _global_
defaults:
  - override /data: vdpt/tartanair_vkitti_disp
  - override /model: nvdpt/nvdpt
  - override /callbacks: 
    - model_checkpoint_simple
    - train_speed_timer
    - lr_monitor

pl_trainer:
  precision: 16-mixed
  max_epochs: 100
  log_every_n_steps: 50
  accumulate_grad_batches: 1 # 32 data, 2 batch, 8gpus, 4 nodes
  limit_val_batches: 0

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir} # /save_dir/name/version/sub_dir
  name: ""
  version: "tb" # merge name and version

task: nvdpt
exp_name: nvdpt