defaults:
  - /pipeline: nvdpt_pipeline 
  # choices are under common/optimizer & scheduler_cfg
  - common/optimizer@optimizer: adam_1e-5
  - common/scheduler_cfg@scheduler_cfg: null

_target_: lib.model.nvdpt.nvdpt_model.NVDPTModel

args:
  seed: ${seed}
  rng_type: seed_plus_idx # [const, random, seed_plus_idx]
  output_dir: ${output_dir}/results
  save_tag: ${save_tag}