# @package _global_
defaults:
  - override /data: mvs/naive_hypersim_ai_001_010
  - override /model: mvs/naive_diffmvs
  - override /callbacks: 
    - model_checkpoint_simple
    - train_speed_timer

pl_trainer:
  precision: 16-mixed
  limit_train_batches: 10000
  limit_val_batches: 100
  max_epochs: 100
  log_every_n_steps: 50
  # accumulate_grad_batches: 1 # ! 1 if use 8 GPUs
  accumulate_grad_batches: 32 # ! 32 if use only one GPU and MVS hypersim dataset

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir}
  name: ""
  version: "tb" # merge name and version

task: mvs
exp_name: naive_diffmvs_ai_001_010
