# @package _global_
defaults:
  - override /data: depth_estimation/train_hypersim_arkitscenes_test_arkitscenes
  - override /model@model: depth_estimation/depth_anything
  - override /callbacks: 
    - model_checkpoint_simple
    - train_speed_timer

pl_trainer:
  precision: 32
  limit_train_batches: 10000
  limit_val_batches: 300
  max_epochs: 100
  log_every_n_steps: 50
  accumulate_grad_batches: 1 # * 8 if use only one gpu
  strategy: ddp_find_unused_parameters_true

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir} # /save_dir/name/version/sub_dir
  name: ""
  version: "tb" # merge name and version

task: depth_estimation
exp_name: depth_anything_vits


model:
  pipeline:
    encoder: 'vits'
    features: 64
    out_channels: [48, 96, 192, 384]
    load_pretrain_backbone: null
    # load_pretrain_net: ${oc.env:workspace}/cache_models/depth_anything/checkpoints/v2_model_vits.pth
    load_pretrain_net: /mnt/bn/liheyang/model_zoo/v2_vits_518_joint.pth
    # use_clstoken: True