# @package _global_
defaults:
  - override /data: depth_estimation/hypersim_scannetpp_arkitscenes
  - override /model@model: depth_estimation/depth_anything
  - override /callbacks: 
    - model_checkpoint_simple
    - train_speed_timer

pl_trainer:
  precision: 32
  limit_train_batches: 1000
  limit_val_batches: 100
  max_epochs: 200
  log_every_n_steps: 50
  accumulate_grad_batches: 1 # * 8 if use only one gpu
  strategy: ddp_find_unused_parameters_true
  devices: 8

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir} # /save_dir/name/version/sub_dir
  name: ""
  version: "tb" # merge name and version

task: depth_estimation
exp_name: july_hypersim_baseline0717_minmax_grad2

model:
  pipeline:
    _target_: lib.model.depth_estimation.depth_anything.depth_anything_upsample_fusion.DepthAnythingPipeline
    range_ratio: [1., 0., 0.] # 8x, 192x256, 8x--192x256
    block_type: 'featurefusiondepthblock'
    # encoder: 'vits'
    # features: 64
    # out_channels: [48, 96, 192, 384]
    load_pretrain_backbone: null
    load_pretrain_net: ${oc.env:workspace}/cache_models/depth_anything/checkpoints/v2_model_metric_ftlht.ckpt
    normalize_disp_type: minmax
    add_grad: False
    grad_tags: ['HyperSim', 'ARKitScenes', 'scannetpp']
    loss_cfg:
      _target_: lib.model.depth_estimation.depth_anything.loss.L1loss_Gradient_upsample
      gradient_weight: 2.