# @package _global_
defaults:
  - override /data: depth_estimation/scannetpp_v3
  - override /model@model: depth_estimation/depth_anything
  - override /callbacks: 
    - model_checkpoint_simple
    - train_speed_timer

pl_trainer:
  precision: 32
  limit_train_batches: 1000
  limit_val_batches: 100
  max_epochs: 500
  log_every_n_steps: 50
  accumulate_grad_batches: 1 # * 8 if use only one gpu
  strategy: ddp_find_unused_parameters_true
  devices: 8

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir} # /save_dir/name/version/sub_dir
  name: ""
  version: "tb" # merge name and version

task: depth_estimation
exp_name: june_depthanythingmetric_scannetpp_perscene

# data:
#   loader_opts:
#     train:
#       - batch_size: 2
#         num_workers: 4
#       - batch_size: 2
#         num_workers: 4
model:
  pipeline:
    _target_: lib.model.depth_estimation.depth_anything.depth_anything_upsample_fusion.DepthAnythingPipeline
    range_ratio: [1., 0., 0.] # 8x, 192x256, 8x--192x256
    block_type: 'featurefusiondepthblock'
    load_pretrain_backbone: null
    load_pretrain_net: ${oc.env:workspace}/cache_models/depth_anything/checkpoints/v2_model_metric_ftlht.ckpt
    normalize_disp_type: minmax
    loss_cfg:
      _target_: lib.model.depth_estimation.depth_anything.loss.L1loss_Gradient_upsample
      gradient_weight: 0.5

callbacks:
  model_checkpoint:
    every_n_epochs: 50 # number of epochs between checkpoints

data:
  train_loader_opts:
    batch_size: 2
  train_dataset:
    dataset_opts: 
      _target_: lib.dataset.depth_estimation.scannetpp_v3.Dataset
      split_path: '/mnt/bn/haotongdata/Datasets/scannetpp/splits/test_meta_data.json'
      scene: 5f99900f09
      split: 'train'
      width: 1008
      height: 756
      resize_target: True
      ensure_multiple_of: 14
  val_dataset:
    dataset_opts:
      _target_: lib.dataset.depth_estimation.scannetpp_v3.Dataset
      split_path: '/mnt/bn/haotongdata/Datasets/scannetpp/splits/test_meta_data.json'
      split: 'val'
      width: 1008
      scene: 5f99900f09
      height: 756
      resize_target: True
      frames: [0, -1, 25]
      ensure_multiple_of: 14