# @package _global_
defaults:
  - override /data: depth_estimation/train_hypersim_test_hypersim_arkitscenes
  - override /model@model: depth_estimation/marigold
  - override /callbacks: 
    - model_checkpoint_simple
    - train_speed_timer

pl_trainer:
  precision: 16-mixed
  limit_train_batches: 10000
  limit_val_batches: 100
  max_epochs: 100
  log_every_n_steps: 50
  accumulate_grad_batches: 1 # * 8 if use only one gpu
  num_sanity_val_steps: -1
  check_val_every_n_epoch: 5

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir} # /save_dir/name/version/sub_dir
  name: ""
  version: "tb" # merge name and version

task: depth_estimation
exp_name: marigold_upsample_noise_gaussian

model:
  pipeline:
    _target_: lib.model.depth_estimation.marigold.marigold_upsample.MarigoldUpsamplePipeline
    zerosft:
      _target_: lib.model.mde.utils.zerosft.ZeroSFT
      label_nc: 5
      norm_nc: 4
    range_ratio: [0.5, 0.3, 0.2] # 8x, 192x256, 8x--192x256
    noise_model:
      _target_: lib.model.depth_estimation.noise.noise_gaussian.NoiseGaussian
      mean: 0.
      std: 0.05




