# @package _global_
defaults:
  - override /data: depth_estimation/hypersim_transform
  - override /model@model: depth_estimation/diffusion_depth
  - override /callbacks: 
    - model_checkpoint_simple
    - train_speed_timer

pl_trainer:
  precision: 32
  limit_train_batches: 5000
  limit_val_batches: 100
  max_epochs: 100
  log_every_n_steps: 50
  accumulate_grad_batches: 1 # * 8 if use only one gpu
  # strategy: ddp_find_unused_parameters_true
  devices: 8

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir} # /save_dir/name/version/sub_dir
  name: ""
  version: "tb" # merge name and version

task: depth_estimation
# exp_name: may_depthanything_vits_arkitscenes_silog
exp_name: may_diffusion_depth

data:
  dataset_opts:
    train:
      train_crop_size: 512
    val:
      ensure_multiple_of: 8
  loader_opts:
    train:
      batch_size: 2
      num_workers: 4