# @package _global_
defaults:
  - override /data: depth_estimation/train_hypersim_test_arkitscenes
  - override /model@model: depth_estimation/marigold
  - override /callbacks: 
    - model_checkpoint_simple
    - train_speed_timer

pl_trainer:
  precision: 16-mixed
  limit_train_batches: 10000
  limit_val_batches: 100
  max_epochs: 100
  log_every_n_steps: 50
  accumulate_grad_batches: 1 # * 8 if use only one gpu

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir} # /save_dir/name/version/sub_dir
  name: ""
  version: "tb" # merge name and version

task: depth_estimation
exp_name: may_marigold_upsample_meanstd_0.01

model:
  pipeline:
    _target_: lib.model.depth_estimation.marigold.marigold_upsample.MarigoldUpsamplePipeline
    zerosft:
      _target_: lib.model.mde.utils.zerosft.ZeroSFT
      label_nc: 5
      norm_nc: 4
    range_ratio: [1., 0., 0., 0.] # 8x, 192x256, 8x--192x256, 8x-4x
    add_cone_noise: True
    cone_noise_std: 0.01
    min_percentile: 0.02
    max_percentile: 0.98

data:
  dataset_opts:
    train:
      train_crop_size: 640
      down_scale: 8
    val:
      ensure_multiple_of: 8
  loader_opts:
    train:
      batch_size: 4
      num_workers: 4
