# @package _global_
# mini的意思是数据mini
defaults:
  - override /data: depth_estimation/v3_data_1
  - override /model@model: depth_estimation/marigold
  - override /callbacks: 
    - model_checkpoint_simple
    - train_speed_timer
pl_trainer:
  precision: 16-mixed
  limit_train_batches: 10000
  limit_val_batches: 100
  max_epochs: 100
  log_every_n_steps: 50
  accumulate_grad_batches: 1 
  devices: 1
  num_nodes: 1
  # marigold至少需要32个data在一个batch中，batch_size * devices * num_nodes * accumulate_grad_batches
  # strategy: ddp_find_unused_parameters_true

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir} # /save_dir/name/version/sub_dir
  name: ""
  version: "tb" # merge name and version

task: depth_estimation
exp_name: marigold