# @package _global_
defaults:
  - override /data: depth_estimation/hypersim_v3
  - override /model@model: depth_estimation/depth_anything
  - override /callbacks: 
    - model_checkpoint_simple
    - train_speed_timer

pl_trainer:
  precision: 32
  limit_train_batches: 1000
  limit_val_batches: 1000
  max_epochs: 100
  log_every_n_steps: 50
  accumulate_grad_batches: 1 # * 8 if use only one gpu
  strategy: ddp_find_unused_parameters_true
  devices: 8

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir} # /save_dir/name/version/sub_dir
  name: ""
  version: "tb" # merge name and version

task: depth_estimation
exp_name: sep_cross_disp

model:
  pipeline:
    _target_: lib.model.depth_estimation.depth_anything.depth_anything.DepthAnything
    load_pretrain_backbone: null
    load_pretrain_net: ${oc.env:workspace}/cache_models/depth_anything/checkpoints/v2_model.pth
    output_act: relu
    disp: True
    warp_func:
      _target_: lib.model.depth_estimation.depth_anything.depth_warp.WarpFixMinMax
      near_depth: 0.
      max_depth: 20.


data:
  _target_: lib.datamodule.general_datamodule_v3.GeneralDataModule
  train_dataset:
    dataset_opts: 
      _target_: lib.dataset.depth_estimation.hypersim_v3.Dataset
      data_root: ${oc.env:workspace}/hypersim
      rgb_dir: ${oc.env:workspace}/datasets/HyperSim
      dpt_dir: ${oc.env:workspace}/processed_datasets/HyperSim
      split_path: ${oc.env:workspace}/processed_datasets/HyperSim/metadata_valid_0.05_splits_ht_new.json
      split: 'val'
      scene: ai_001_010
      frames: [0, -1, 1]
      transforms:
        - _target_: lib.dataset.depth_estimation.transform.Resize
          ensure_multiple_of: 14
          width: 1008
          height: 756
          resize_target: True
        - _target_: lib.dataset.depth_estimation.transform.PrepareForNet
        # - _target_: lib.dataset.depth_estimation.transform.SimLowRes
        #   height: 192
        #   width: 256
  val_dataset:
    dataset_opts:
      _target_: lib.dataset.depth_estimation.hypersim_v3.Dataset
      data_root: ${oc.env:workspace}/hypersim
      rgb_dir: ${oc.env:workspace}/datasets/HyperSim
      dpt_dir: ${oc.env:workspace}/processed_datasets/HyperSim
      split_path: ${oc.env:workspace}/processed_datasets/HyperSim/metadata_valid_0.05_splits_ht_new.json
      split: 'val'
      scene: ai_001_010
      frames: [0, -1, 1]
      transforms:
        - _target_: lib.dataset.depth_estimation.transform.Resize
          ensure_multiple_of: 14
          width: 1008
          height: 756
          resize_target: True
        - _target_: lib.dataset.depth_estimation.transform.PrepareForNet
  train_loader_opts:
    batch_size: 2