# @package _global_
defaults:
  - override /data: dpt/hypersim_vkitti
  - override /model: marigold/marigold
  - override /callbacks: 
    - model_checkpoint_every10ks
    - train_speed_timer
    - lr_monitor

pl_trainer:
  precision: 16-mixed
  max_epochs: 50
  log_every_n_steps: 50
  accumulate_grad_batches: 1
  limit_train_batches: 10000

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir} # /save_dir/name/version/sub_dir
  name: ""
  version: "tb" # merge name and version

task: marigold
exp_name: marigold