defaults:
  - /pipeline: mdemarigold_upsample_pipeline_dpt
  - common/optimizer@optimizer: adam_1e-5
  - common/scheduler_cfg@scheduler_cfg: null
_target_: lib.model.mde.mde_model.MdeModel
args:
  seed: ${seed}
  rng_type: seed_plus_idx # [const, random, seed_plus_idx]
  output_dir: ${output_dir}/results
  save_tag: ${save_tag}
  lr_table:
    pretrained: 1e-5