defaults:
  - /model/common/optimizer@optimizer: adamw_1e-4
  - /model/common/optimizer@lr_table: lr_table
  - /model/common/scheduler_cfg@scheduler_cfg: null
_target_: lib.model.depth_estimation.depth_estimation_model.DepthEstimationModel
output_dir: ${output_dir}/results
save_orig_pred: False
save_vis_depth: True
save_vis_depth_and_concat_img: True
compute_abs_metric: True
compute_rel_metric: True
ransac_align_depth: True

pipeline:
  _target_: lib.model.depth_estimation.diffusion_depth.diffusion_depth.DiffusionDepth
  scheduler_opt_train: # Always DDPM
    _class_name: "DDPMScheduler"
    _diffusers_version: "0.8.0"
    beta_end: 0.012
    beta_schedule: "scaled_linear"
    beta_start: 0.00085
    clip_sample: False
    num_train_timesteps: 1000
    prediction_type: "v_prediction"
    # set_alpha_to_one: False
    # skip_prk_steps: True
    steps_offset: 1
    trained_betas: null
  scheduler_opt_test:
    _class_name: "DDIMScheduler"
    _diffusers_version: "0.8.0"
    beta_end: 0.012
    beta_schedule: "scaled_linear"
    beta_start: 0.00085
    clip_sample: False
    num_train_timesteps: 1000
    prediction_type: "v_prediction"
    set_alpha_to_one: False
    # skip_prk_steps: True
    steps_offset: 1
    trained_betas: null
  unet_opt:
    _class_name: "UNet"
    _diffusers_version: "0.20.1"
    act_fn: "silu"
    attention_head_dim: [5, 10, 20, 20]
    block_out_channels: [64, 128, 256, 256]
    center_input_sample: false
    cross_attention_dim: 1024
    down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D", "CrossAttnDownBlock2D"]
    downsample_padding: 1
    dual_cross_attention: false
    flip_sin_to_cos: true
    freq_shift: 0
    in_channels: 4
    layers_per_block: 2
    mid_block_scale_factor: 1
    norm_eps: 1e-05
    norm_num_groups: 32
    out_channels: 1
    sample_size: 96
    up_block_types: ["CrossAttnUpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D"] 
    use_linear_projection: true
  tokenizer_opt:
    config_dir: ${oc.env:workspace}/Marigold/checkpoint/Marigold_v1_merged_2/tokenizer
  textencoder_opt:
    config_dir: ${oc.env:workspace}/Marigold/checkpoint/Marigold_v1_merged_2/text_encoder