defaults:
  - /model/common/optimizer@optimizer: adamw_1e-5
  - /model/common/optimizer@lr_table: lr_table
  - /model/common/scheduler_cfg@scheduler_cfg: null
_target_: lib.model.depth_estimation.depth_estimation_model.DepthEstimationModel
output_dir: ${output_dir}/results
save_orig_pred: False
save_vis_depth: True
save_vis_depth_and_concat_img: True
compute_abs_metric: False
compute_rel_metric: True
ransac_align_depth: True

pipeline:
  _target_: lib.model.depth_estimation.marigold.marigold.MarigoldPipeline
  scheduler_opt_train: # Always DDPM
    _class_name: "DDPMScheduler"
    _diffusers_version: "0.8.0"
    beta_end: 0.012
    beta_schedule: "scaled_linear"
    beta_start: 0.00085
    clip_sample: False
    num_train_timesteps: 1000
    prediction_type: "v_prediction"
    # set_alpha_to_one: False
    # skip_prk_steps: True
    steps_offset: 1
    trained_betas: null
  scheduler_opt_test:
    _class_name: "DDIMScheduler"
    _diffusers_version: "0.8.0"
    beta_end: 0.012
    beta_schedule: "scaled_linear"
    beta_start: 0.00085
    clip_sample: False
    num_train_timesteps: 1000
    prediction_type: "v_prediction"
    set_alpha_to_one: False
    # skip_prk_steps: True
    steps_offset: 1
    trained_betas: null
  unet_opt:
    config_dir: ${oc.env:workspace}/cache_models/Marigold/checkpoint/marigold-v1-0/unet
  vae_opt:
    config_dir: ${oc.env:workspace}/cache_models/Marigold/checkpoint/marigold-v1-0/vae
  tokenizer_opt:
    config_dir: ${oc.env:workspace}/cache_models/Marigold/checkpoint/marigold-v1-0/tokenizer
  textencoder_opt:
    config_dir: ${oc.env:workspace}/cache_models/Marigold/checkpoint/marigold-v1-0/text_encoder