defaults:
  - /pipeline: stereo_pipeline 
  - common/optimizer@optimizer: adam_1e-5
  - common/scheduler_cfg@scheduler_cfg: null
_target_: lib.model.stereo.stereo_model.StereoModel
args:
  seed: ${seed}
  rng_type: seed_plus_idx # [const, random, seed_plus_idx]
  output_dir: ${output_dir}/results
  save_tag: ${save_tag}
  lr_table:
    output_conv: 1e-4