# ================================ #
#             override             #
# ================================ #
# specify default configuration; the order determines the override order
defaults:
  - _self_
  # pytorch-lightning
  - data: ???
  - model: ???
  - callbacks: null
  # system
  - hydra: default
  # global-override
  - exp: ???  # set "data, model and callbacks" in yaml
  - global/task: null  # dump
  - global/hsearch: null  # hyper-param search
  - global/debug: null

# ================================ #
#          global setting          #
# ================================ #
# expirement information
entry: train_net
task: ??? 
exp_name: ???
save_tag: default

# utilities in the entry file
output_dir: ${oc.env:workspace,'data/pl_htcode'}/outputs/${task}/${exp_name}
ckpt_path: null
ckpt_type: null
seed: 42
print_cfg: True
resume_training: True
confirm_delete_previous_dir: False # 请小心使用

# lightning default settings
pl_trainer:
  devices: 1
  num_nodes: 1
  num_sanity_val_steps: 0 # disable sanity check

logger: null