# @package _global_
defaults:
  - /model: stereo/image
  - override /data: stereo/diml
  - override /callbacks: 
    - model_checkpoint_every10ks
    - train_speed_timer
    - lr_monitor

pl_trainer:
  precision: 16-mixed
  max_epochs: 10000
  log_every_n_steps: 50
  accumulate_grad_batches: 16
  limit_val_batches: 0

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir} # /save_dir/name/version/sub_dir
  name: ""
  version: "tb" # merge name and version

task: stereo
exp_name: image