# @package _global_
defaults:
  - override /data: lidarerr/arkitscenes
  - override /model: lidarerr/diffusion
  - override /callbacks: 
    - model_checkpoint_simple
    - train_speed_timer

pl_trainer:
  precision: 16-mixed
  limit_val_batches: 200
  max_epochs: 1000
  log_every_n_steps: 50
  accumulate_grad_batches: 24

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir} # /save_dir/name/version/sub_dir
  name: ""
  version: "tb" # merge name and version

task: lidarerr
exp_name: diffusion_only_dpt_attn2_normalize

model:
  pipeline:
    args:
      only_dpt: True
      normal_dpt: True
      unet_opt:
        in_channels: 4
        out_channels: 1
        down_block_types: ["DownBlock2D", "DownBlock2D", "CrossAttnDownBlock2D", "CrossAttnDownBlock2D"]
        up_block_types: ["CrossAttnUpBlock2D", "CrossAttnUpBlock2D", "UpBlock2D", "UpBlock2D"] 

data:
  loader_opts:
    train:
      - batch_size: 2
        num_workers: 2
        shuffle: True
        persistent_workers: True
        drop_last: True
      - batch_size: 2
        num_workers: 2
        shuffle: True
        persistent_workers: True
        drop_last: True

      