# @package _global_
defaults:
  - override /data: lidarerr/arkitscenes
  - override /model: lidarerr/diffusion
  - override /callbacks: 
    - model_checkpoint_simple
    - train_speed_timer

pl_trainer:
  precision: 16-mixed
  limit_val_batches: 200
  max_epochs: 1000
  log_every_n_steps: 50
  accumulate_grad_batches: 2

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir} # /save_dir/name/version/sub_dir
  name: ""
  version: "tb" # merge name and version

task: lidarerr
exp_name: diffusion_only_dpt_normalize_yd

model:
  pipeline:
    args:
      only_dpt: True
      normal_dpt: True
      hydra_unet: True
      ivid_unet_opt:
        __target__: lib.network.ivid.adm.AdmUnet2d
        image_size: 256 # 忽略它
        in_channels: 4
        out_channels: 1
        model_channels: 128
        num_res_blocks: 2
        num_classes: null
        has_null_class: false
        channel_mult: [1, 1, 2, 3, 4]
        attention_resolutions: [32, 16, 8]
        num_groups: 32
        num_heads: null
        num_head_channels: 64
        dropout: 0.0
        use_fp16: false

data:
  loader_opts:
    train:
      - batch_size: 8
        num_workers: 5
        shuffle: True
        persistent_workers: True
        drop_last: True
      - batch_size: 8
        num_workers: 5
        shuffle: True
        persistent_workers: True
        drop_last: True

# "num_res_blocks": 2,
#             "num_classes": null,
#             "has_null_class": false,
#             "channel_mult": [1, 1, 2, 3, 4],
#             "attention_resolutions": [32, 16, 8],
#             "num_groups": 32,
#             "num_heads": null,
#             "num_head_channels": 64,
#             "dropout": 0.0,
#             "use_fp16": true


      