# @package _global_
defaults:
  - override /data: lidarerr/arkitscenes
  - override /model: lidarerr/diffusion
  - override /callbacks: 
    - model_checkpoint_simple
    - train_speed_timer

pl_trainer:
  precision: 16-mixed
  limit_val_batches: 200
  max_epochs: 1000
  log_every_n_steps: 50
  accumulate_grad_batches: 1

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir} # /save_dir/name/version/sub_dir
  name: ""
  version: "tb" # merge name and version

task: lidarerr
exp_name: diffusion_only_dpt_attn_normalize_epsilon

model:
  pipeline:
    args:
      only_dpt: True
      normal_dpt: True
      unet_opt:
        in_channels: 4
        out_channels: 1
        down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D", "CrossAttnDownBlock2D"]
        up_block_types: ["CrossAttnUpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D"] 
      scheduler_opt_train:
        prediction_type: 'epsilon'
      scheduler_opt_test:
        prediction_type: 'epsilon'